########################
## Basic Configuration


# Valid values: SuperPerms, Vault
permissions: SuperPerms

# Sign/Chest protection.
# Note that this may interfere with other protection plugins,
# use with caution.
protection:
    signs: true
    chest_break: false
    chest_open: false

# Limits to keep performance sane.
# 'radius' limits are in number of blocks.
# Setting any limit to -1 or 'unlimited' makes it infinite.
limits:
    # How far away you can be when doing a /mondo find
    find_max_radius: 300

    slaves:
        # How many slaves can be added per master.
        per_master: unlimited
        # How far away from a mondo chest the slave can be
        max_add_radius: 150

    mondochests:
        # Allows limiting how many MondoChests(masters)  a given user can make.
        per_user: unlimited


#######################
## Restacking feature

# Allow restacking of materials for the master chest.  Restacking will allow
# various materials which can't stack or stack to less than 64 to be stacked to
# the maximum value.
restack_master: false

# Restack materials for the slave chests if 'restack' is on the second line.
restack_slaves: false

# What materials to restack to the maximum 64
restack_materials:
  - SIGN
  - SNOW_BALL
  - EGG


#####################
## Specialty options

special:
    # signs look for slaves up and down two from the sign.
    # This allows you to hide signs in the floor or ceiling.
    slave_vertical_two: false

    # signs look 2 to the left and right.
    slave_horizontal_two: false
