# How far from the master chest to search for slave chests.
# an X radius of 20 blocks means 20 blocks plus or minus in either direction
# from the block in question.
chest_search:
    radiusX: 5
    radiusY: 1
    radiusZ: 5

# Allow restacking of materials for the master chest.  Restacking will allow
# various materials which can't stack or stack to less than 64 to be stacked to
# the maximum value.
restack_master: false

# Restack materials for the slave chests if 'restack' is on the second line.
restack_slaves: false

# What materials to restack to the maximum 64
restack_materials:
  - SIGN
  - SNOW_BALL
  - EGG

# Valid values: false/none, SuperPerms, Vault
permissions: false

# Enable sign protection.
# Note that this may interfere with other protection plugins,
# use with caution.
sign_protection: false


# Constraints on the search algorithm's Y coordinate
# This is here because the Y-max is going to increase
# in MC 1.2 and we want to be ready.
world_constraints:
    Ymin: 0
    # Set Ymax to -1 to have the code use world.getMaxHeight(). This should
    # work in 1.1 and 1.2 just fine, but the option exists to override just in
    # case you want different behavior.
    Ymax: -1

