name: MondoChest
main: us.crast.mondochest.MondoChest
version: 0.3
author: Crast
description: "Sort your items into appropriate chests"
website: "http://dev.bukkit.org/server-mods/mondochest/"

permissions:
    mondochest.*:
        description: Perform all MondoChest actions
        children:
            mondochest.create_master: true
            mondochest.add_slave: true
            mondochest.use: true
    mondochest.create_master:
        description: Create a new MondoChest bank
        default: op
    mondochest.add_slave:
        description: Manually add new MondoSlaves
        default: op
    mondochest.use:
        default: true

# vim: ts=4 sw=4 sts=4 expandtab
