permissions: SuperPerms

protection:
    signs: true
    chest_break: true
    chest_open: false

acl_fallback_role: configure_me

limits:
    find_max_radius: 300
    mondochests_per_user: unlimited
    slaves_per_master: unlimited
    slave_max_add_radius: 150

restack_master: false
restack_slaves: false
restack_materials: []

special:
    slave_vertical_two: false
    slave_horizontal_two: false
    sign_in_front: false
    case_insensitive_signs: false
